public with sharing class ApexLearning_DataType_01 {

    // Class Name and Constructor Name should be the same
    //To execute this ApexLearning_DataType_01 var = new ApexLearning_DataType_01();
    Public  ApexLearning_DataType_01 (){
        System.debug('I am in Constructor');
    }

    //In method we can give different name to it.
    public void ApexLearning_DataType_01() {
        System.debug('I am in method');

    }
}