public class SetList {
    public static void SetMethod()
    {
        // creating and initializing an Integer set
        
        Set <Integer> s1=  new Set<Integer>();
        s1.add(11);
        s1.add(12);
        s1.add(13);
        s1.add(14);
        s1.add(15);
        
        //Initializing and adding values together
        
        Set <Integer> s2 = new Set<Integer>{21,22,23,24 , 24};
            
        //A string set type
        
        Set <String> s3 = new Set<String>{'Akshay' , 'Vijay' , 'Shubham'};
            
            
        
    }

}